#ifndef __AUTOVERSION__
#define __AUTOVERSION__
#include "revision.h"
#define AUTO_UPDATE_VERSION
#define VER_MAJOR 1
#define VER_MINOR 0
#define VER_REVISION AUTO_FILE_REVISION

#define AUTO_VERSION VER_MAJOR, VER_MINOR, 0, AUTO_FILE_REVISION
#define AUTO_FILE_VERSION VER_MAJOR, VER_MINOR, 0, AUTO_FILE_REVISION
#define AUTO_PRODUCT_VERSION VER_MAJOR, VER_MINOR, 0, AUTO_PRODUCT_REVISION
#define AUTO_VERSION_FILE_FULL_STR "1.0.0." AUTO_FILE_REVISION_STR
#define AUTO_VERSION_PRODUCT_FULL_STR "1.0.0." AUTO_PRODUCT_REVISION_STR

#endif

